version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.2-3.0.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "4320:3306"
    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - db-data:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/drupal:8-7.1-3.3.2
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      DB_DRIVER: mysql
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting below
      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
      APP_ENV: 'development'
    volumes:
      - .:/var/www/html:cached
      - ${VOLUMES_PATH}/drupal_files/public:/var/www/html/web/sites/default/files
      - ${VOLUMES_PATH}/drupal_files/private:/var/drupal_files/private

  nginx:
    image: wodby/drupal-nginx:8-1.13-3.0.2
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_SERVER_NAME: "imfaber-cms"
    volumes:
      - .:/var/www/html:cached
      - ${VOLUMES_PATH}/drupal_files/public:/var/www/html/web/sites/default/files
      - ${VOLUMES_PATH}/drupal_files/private:/var/drupal_files/private
    labels:
      - 'traefik.backend=imfabercms_nginx_1'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:imfaber-cms.docker.localhost'

#  node:
#    image: node:6.11-alpine
#    working_dir: /var/www/html
#    volumes:
#      - .:/var/www/html:cached
#    command: sh -c 'npm run init'

  theme:
    image: kkarczmarczyk/node-yarn:8.0
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
    command: sh -c 'yarn run init'
    ports:
      - "3010:3000"
      - "3011:3001"

  solr:
    image: wodby/drupal-solr:8-6.6-2.2.0
    environment:
      SOLR_HEAP: 1024m
    labels:
      - 'traefik.backend=solr'
      - 'traefik.port=8983'
      - 'traefik.frontend.rule=Host:solr.imfaber-cms.docker.localhost'
    volumes:
      - ${VOLUMES_PATH}/solr:/opt/solr/server/solr

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.imfaber-cms.docker.localhost'

  portainer:
    image: portainer/portainer
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.imfaber-cms.docker.localhost'

  redis:
    image: wodby/redis:4.0-2.1.3

#  traefik:
#    image: traefik
#    command: -c /dev/null --web --docker --logLevel=INFO
#    ports:
#      - '8000:80'
#      - '8080:8080' # Dashboard
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  db-data:
## Docker-sync for macOS users
#  docker-sync:
#    external: true
