<?php

/**
 * @file
 * Contains imfaber_global.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function imfaber_global_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the imfaber_global module.
    case 'help.page.imfaber_global':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Helper and utilities with global scope') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function imfaber_global_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'imfaber_global/imfaber_global.admin';
}

/**
 * Implements hook_form_alter().
 */
function imfaber_global_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (!empty($form['slug'])) {
    $form['slug_group'] = [
      '#type' => 'details',
      '#title' => t('URL slug'),
      '#group' => 'advanced',
      '#weight' => 999,
      '#optional' => false,
    ];
    $form['slug']['#group'] = 'slug_group';
  }
}